steps:
    # build the container image using the provided Dockerfile
    # (cf. https://docs.docker.com/engine/reference/commandline/build/ )
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/toolbox', '-f', 'Dockerfile-googleclouddeploy', '.']
    # push the container image into the project's gcr.io registry
    # (cf. https://docs.docker.com/engine/reference/commandline/push/ )
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/toolbox']
    # deploy container to Cloud Run 
    # (cf. https://cloud.google.com/sdk/gcloud/reference/run/deploy )
  - name: "gcr.io/cloud-builders/gcloud"
    args: [
      'run', 'deploy', 'toolbox-${_STAGE}',
      '--image=gcr.io/$PROJECT_ID/toolbox',
      '--region=europe-west4',
      '--platform=managed',
      '--allow-unauthenticated',
      '--max-instances=4',
      '--set-env-vars=GCP_CLOUD_SQL_INSTANCE_CONNECTION_NAME=${_GCP_CLOUD_SQL_INSTANCE_CONNECTION_NAME}',
      '--set-env-vars=GCP_CLOUD_SQL_DATABASE_NAME=${_STAGE}',
      '--set-env-vars=TOOLBOX_BUILD_VERSION=${_TOOLBOX_BUILD_VERSION}',
      '--update-secrets=GCP_CLOUD_SQL_INSTANCE_DATASOURCE_PASSWORD=postgres_password:latest']