# Use the official OpenJDK Latest base image
FROM openjdk:latest

# Set the working directory in the container
WORKDIR /app

# Copy the JAR file into the container
COPY toolbox-0.0.1-SNAPSHOT.jar /app/toolbox.jar

# Expose the port the application runs on
EXPOSE 8080

# Define the command to run your application
CMD ["java", "-jar", "toolbox.jar"]